---

- hosts: all

  tasks:
    - pacman:
        name: "{{ item }}"
        state: latest
      ignore_errors: true
      become: true
      with_items:
        - telegram-desktop
        - ripgrep
        - the_silver_searcher
        - zsh
        - fzf
        # - libpq-dev
        # - python-dev
        # - python3-dev
        - kitty
    - pip:
        extra_args: "--user"
        name: '{{ item }}'
        state: latest
      with_items:
        - neovim
        - pylint
        - ansible-lint
        - yamllint
        - bashate
        - sexpdata
        - websocket-client
        - jedi
        - psutil
        - yamllint
        - setproctitle
      tags:
        - all

    - gem: name={{ item }} state=latest
      # become: true
      ignore_errors: true
      with_items:
        - bundler
        - ripper-tags
        - slim_lint
        - rake
        - neovim
        - mdl
        - sqlint
        - rubocop
        - solargraph
        - mailcatcher
        - language_server
        - brakeman
        - rails_best_practices
        - reek
        - fastri
      tags:
        - all
        - ruby

    - npm: name={{ item }} global=true state=latest
      become: true
      ignore_errors: true
      with_items:
        - yaml-language-server
        - javascript-typescript-langserver
        - prettier
        - htmlhint
        - typescript
        - typings
        - pug-lint
        - livedown
        - js-yaml
        - stylelint
        - js-beautify
        - jsonlint
        - eslint
        - neovim
        - babel-eslint
        - eslint-plugin-jest
        - eslint-plugin-flowtype
        - eslint-plugin-import
        - eslint-import-resolver-webpack
        - eslint-plugin-markdown
        - eslint-plugin-jsx-a11y
        - eslint-config-airbnb
        - eslint-config-airbnb-base
        - eslint-plugin-react
        - eslint-plugin-babel
        - eslint-plugin-jest
      tags:
        - all
        - eslint

    - copy:
        src: ./files/eslintrc
        dest: ~/.eslintrc
        backup: true
      tags:
        - all
        - eslint


    - file:
        dest: ~/.elixir.d/elixir-ls
        state: directory
      tags: elixir

    - unarchive:
        src: "https://github.com/JakeBecker/elixir-ls/releases/download/v0.2.24/elixir-ls.zip"
        dest: ~/.elixir.d/elixir-ls
        remote_src: true
      tags: elixir
