---
- hosts: all
  tasks:
    - file:
        force: yes
        src: "{{ curdir }}/files/{{ item }}"
        dest: ~/.{{ item }}
        state: link
      with_items:
        - zshrc
        - tigrc
        - inputrc
        - tmux.conf
        - xinitrc

    - file:
        force: yes
        src: "{{ curdir }}/files/kitty.conf"
        dest: ~/.config/kitty/kitty.conf
        state: link

    - file:
        force: yes
        src: "{{ curdir }}/files/flake8"
        dest: ~/.config/flake8
        state: link

    - git:
        repo: https://github.com/zsh-users/antigen.git
        dest: ~/.zsh/antigen
