---
- hosts: all
  tasks:
    - file:
        force: yes
        src: '{{ curdir }}/files/{{ item }}'
        dest: ~/.{{ item }}
        state: link
      with_items:
        - zshrc
        - tigrc
        - gitignore
        - gemrc
        - inputrc
        - tmux.conf
        - xinitrc

    - file:
        force: yes
        src: '{{ curdir }}/files/flake8'
        dest: ~/.config/flake8
        state: link

    - file:
        force: yes
        path: ~/.config/alacritty
        state: directory

    - file:
        force: yes
        src: '{{ curdir }}/files/alacritty.yml'
        dest: ~/.config/alacritty/alacritty.yml
        state: link

    - file:
        force: yes
        path: ~/.config/kitty
        state: directory

    - file:
        force: yes
        src: '{{ curdir }}/files/kitty.conf'
        dest: ~/.config/kitty/kitty.conf
        state: link

    - file:
        force: yes
        path: ~/.config/gitui
        state: directory

    - file:
        force: yes
        src: '{{ curdir }}/files/gitui.ron'
        dest: ~/.config/gitui/key_config.ron
        state: link
