# Enable Powerlevel10k instant prompt. Should stay close to the top of zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

xset r rate 175 67
# zmodload zsh/zprof
source $HOME/dotfiles/zsh/env
source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/settings
source $HOME/dotfiles/zsh/plugins
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
source $HOME/dotfiles/zsh/fzf
# zprof
unsetopt share_history

# export ANDROID_HOME='~/Android/Sdk'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey "\e " autosuggest-execute
bindkey '^[.' insert-last-word

autoload -Uz compinit
compinit

. ~/.asdf/plugins/java/set-java-home.zsh

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/vtm/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/vtm/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/vtm/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/vtm/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

