# Enable Powerlevel10k instant prompt. Should stay close to the top of zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

xset r rate 175 67
# zmodload zsh/zprof
source $HOME/dotfiles/zsh/env
source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/settings
source $HOME/dotfiles/zsh/plugins
source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
source $HOME/dotfiles/zsh/fzf
# zprof
unsetopt share_history

# export ANDROID_HOME='~/Android/Sdk'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^[^ ' autosuggest-execute
bindkey "\e " autosuggest-accept
bindkey '^[.' insert-last-word

autoload -Uz compinit
compinit


